# Generated by Django 6.0.1 on 2026-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrepot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True)),
                ('adresse', models.TextField()),
                ('responsable', models.CharField(max_length=150)),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('capacite_totale', models.PositiveIntegerField(help_text='Capacité maximale en unités de stockage')),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Entrepôt',
                'verbose_name_plural': 'Entrepôts',
                'ordering': ['nom'],
            },
        ),
    ]
