# Generated by Django 6.0.1 on 2026-08-22 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Entrepots', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrepot',
            name='latitude',
            field=models.FloatField(default=12.645, help_text='Latitude GPS du dépôt/entrepôt'),
        ),
        migrations.AddField(
            model_name='entrepot',
            name='longitude',
            field=models.FloatField(default=-7.995, help_text='Longitude GPS du dépôt/entrepôt'),
        ),
    ]
