# Generated by Django 6.0.1 on 2026-08-07 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Entrepots', '0001_initial'),
        ('Produits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MouvementStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_mouvement', models.CharField(choices=[('ENTREE', 'Entrée'), ('SORTIE', 'Sortie'), ('TRANSFERT', 'Transfert'), ('AJUSTEMENT', 'Ajustement')], max_length=15)),
                ('quantite', models.IntegerField(help_text='Positif pour entrée, négatif pour sortie')),
                ('reference_document', models.CharField(blank=True, db_index=True, max_length=100)),
                ('date_mouvement', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='Entrepots.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mouvements', to='Produits.produit')),
            ],
            options={
                'verbose_name': 'Mouvement de stock',
                'verbose_name_plural': 'Mouvements de stock',
                'ordering': ['-date_mouvement'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_disponible', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entrepot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='Entrepots.entrepot')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stocks', to='Produits.produit')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('produit', 'entrepot')},
            },
        ),
    ]
