# Generated by Django 6.0.1 on 2026-08-07 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Achats', '0001_initial'),
        ('Ventes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FactureAchat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('RECUE', 'Reçue'), ('VALIDEE', 'Validée'), ('PAYEE', 'Payée'), ('CONTESTEE', 'Contestée')], default='RECUE', max_length=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='Achats.commandeachat')),
            ],
            options={
                'verbose_name': 'Facture achat',
                'verbose_name_plural': 'Factures achat',
                'ordering': ['-date_facture'],
            },
        ),
        migrations.CreateModel(
            name='FactureVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=100, unique=True)),
                ('montant_ht', models.DecimalField(decimal_places=2, max_digits=14)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=18.0, max_digits=5)),
                ('montant_ttc', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_facture', models.DateField()),
                ('date_echeance', models.DateField(blank=True, null=True)),
                ('statut', models.CharField(choices=[('EMISE', 'Émise'), ('ENVOYEE', 'Envoyée'), ('PAYEE', 'Payée'), ('IMPAYEE', 'Impayée'), ('ANNULEE', 'Annulée')], default='EMISE', max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('commande_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='Ventes.commandevente')),
            ],
            options={
                'verbose_name': 'Facture vente',
                'verbose_name_plural': 'Factures vente',
                'ordering': ['-date_facture'],
            },
        ),
    ]
