# Generated by Django 6.0.1 on 2026-08-08 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParametreApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_entreprise', models.CharField(default='Supply Chain', help_text="Nom de l'entreprise affiché dans l'application", max_length=200)),
                ('slogan', models.CharField(blank=True, help_text='Slogan ou sous-titre', max_length=200)),
                ('logo', models.ImageField(blank=True, help_text="Logo affiché dans l'en-tête", null=True, upload_to='logos/')),
                ('email_contact', models.EmailField(blank=True, help_text='Email de contact', max_length=254)),
                ('telephone', models.CharField(blank=True, help_text='Téléphone de contact', max_length=20)),
                ('adresse', models.TextField(blank=True, help_text="Adresse de l'entreprise")),
                ('devise', models.CharField(default='FCFA', help_text='Devise utilisée (ex. FCFA, €, $)', max_length=10)),
                ('pied_de_page', models.TextField(blank=True, help_text='Mention affichée en pied de page des documents')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Paramètre de l'application",
                'verbose_name_plural': "Paramètres de l'application",
            },
        ),
    ]
