# Generated by Django 6.0.1 on 2026-08-22 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Achats', '0001_initial'),
        ('Entrepots', '0001_initial'),
        ('Produits', '0003_produit_quantite'),
        ('Ventes', '0001_initial'),
        ('apps', '0003_parametreapp_couleurs'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuiviExpedition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_suivi', models.CharField(db_index=True, max_length=50, unique=True)),
                ('quantite', models.PositiveIntegerField(default=1)),
                ('statut', models.CharField(choices=[('1_FOURNISSEUR', 'Fournisseur — Commande / Prêt au départ'), ('2_TRANSIT_ENTREPOT', 'Transit — En route vers Entrepôt'), ('3_ENTREPOT', 'Entrepôt — Reçu & En Stock'), ('4_TRANSIT_CLIENT', 'Transit — En cours de livraison Client'), ('5_LIVRE', 'Client — Produit Livré')], default='1_FOURNISSEUR', max_length=30)),
                ('lat_fournisseur', models.FloatField(default=12.6392, help_text='Latitude Fournisseur')),
                ('lng_fournisseur', models.FloatField(default=-8.0029, help_text='Longitude Fournisseur')),
                ('lat_entrepot', models.FloatField(default=12.65, help_text='Latitude Entrepôt')),
                ('lng_entrepot', models.FloatField(default=-7.98, help_text='Longitude Entrepôt')),
                ('lat_client', models.FloatField(default=12.61, help_text='Latitude Client')),
                ('lng_client', models.FloatField(default=-7.95, help_text='Longitude Client')),
                ('lat_actuelle', models.FloatField(default=12.6392, help_text='Latitude actuelle GPS')),
                ('lng_actuelle', models.FloatField(default=-8.0029, help_text='Longitude actuelle GPS')),
                ('vitesse_kmh', models.FloatField(default=0.0, help_text='Vitesse instantanée en km/h')),
                ('progression_pct', models.PositiveIntegerField(default=0, help_text='Progression globale 0-100%')),
                ('transporteur', models.CharField(blank=True, default='Logistique Express', max_length=100)),
                ('immatriculation_vehicule', models.CharField(blank=True, default='M-1234-BK', max_length=50)),
                ('nom_chauffeur', models.CharField(blank=True, default='Moussa Traoré', max_length=100)),
                ('telephone_chauffeur', models.CharField(blank=True, default='+223 70 00 00 00', max_length=20)),
                ('date_expedition', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_estimee', models.DateTimeField(blank=True, null=True)),
                ('date_livraison_effective', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='Ventes.client')),
                ('commande_achat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='Achats.commandeachat')),
                ('commande_vente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='Ventes.commandevente')),
                ('entrepot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='Entrepots.entrepot')),
                ('fournisseur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expeditions', to='Achats.fournisseur')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suivis', to='Produits.produit')),
            ],
            options={
                'verbose_name': "Suivi d'expédition",
                'verbose_name_plural': "Suivis d'expédition",
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PositionGPSHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('vitesse', models.FloatField(default=0.0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_positions', to='apps.suiviexpedition')),
            ],
            options={
                'verbose_name': 'Position GPS',
                'verbose_name_plural': 'Positions GPS',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EtapeSuivi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_etape', models.CharField(max_length=30)),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('lieu', models.CharField(blank=True, max_length=200)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_etape', models.DateTimeField(auto_now_add=True)),
                ('est_terminee', models.BooleanField(default=True)),
                ('expedition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapes', to='apps.suiviexpedition')),
            ],
            options={
                'verbose_name': 'Étape de suivi',
                'verbose_name_plural': 'Étapes de suivi',
                'ordering': ['date_etape'],
            },
        ),
    ]
