# Generated by Django 6.0.1 on 2026-08-07 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=50, unique=True)),
                ('designation', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('prix_unitaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unite_mesure', models.CharField(choices=[('PCS', 'Pièce'), ('KG', 'Kilogramme'), ('L', 'Litre'), ('M', 'Mètre'), ('BOITE', 'Boîte'), ('PALETTE', 'Palette')], default='PCS', max_length=10)),
                ('stock_minimum', models.PositiveIntegerField(default=0)),
                ('actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Produit',
                'verbose_name_plural': 'Produits',
                'ordering': ['designation'],
            },
        ),
    ]
