# Generated by Django 6.0.1 on 2026-08-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produits', '0002_produit_montant_produit_stock_alerte_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
